name: AI Review Agent

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  ai-review:
    uses: rozxckyyy/ai-review-agent/.github/workflows/reusable-ai-review.yml@master
    with:
      gemini_model: gemini-2.5-flash-lite
      python_version: "3.12"
      target_setup_command: |
        python -m pip install --upgrade pip
        pip install pytest
      fail_on_request_changes: true
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}