name: AI Review Agent

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai-review:
    runs-on: ubuntu-latest

    if: >
        github.event_name == 'pull_request' ||
        (
            github.event_name == 'issue_comment' &&
            github.event.issue.pull_request &&
            (
            startsWith(github.event.comment.body, '/agent review') ||
            startsWith(github.event.comment.body, '/agent explain')
            )
        )

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout AI agent repository
        uses: actions/checkout@v4
        with:
          repository: rozxckyyy/ai-review-agent
          path: ai-review-agent

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install agent dependencies
        working-directory: ai-review-agent
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI review agent
        working-directory: ai-review-agent
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-flash-lite
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            if [ "${{ github.event_name }}" = "pull_request" ]; then
                PR_NUMBER="${{ github.event.pull_request.number }}"
                COMMAND="review"
            else
                PR_NUMBER="${{ github.event.issue.number }}"
                COMMENT_BODY="${{ github.event.comment.body }}"

                if [[ "$COMMENT_BODY" == /agent\ explain* ]]; then
                COMMAND="explain"
                else
                COMMAND="review"
                fi
            fi

            python -m src.main pr "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "$PR_NUMBER" --publish --command "$COMMAND"